# ODRA Strategy Configuration

# Data parameters
data:
  raw_path: "odra_strategy/data/raw"  # Updated to correct path
  processed_path: "odra_strategy/data/processed/odra_dataset.pkl"  # Updated to match raw_path structure
  episode_length: 1000  # Number of transactions per episode
  validation_split: 0.2
  test_split: 0.1
  chunk_size: 10000  # Size of chunks for parallel processing

# Feature engineering parameters
features:
  n_jobs: 4  # Number of parallel jobs for feature computation
  alpha_ewma: 0.05  # EWMA decay factor
  tick_spacing: 60  # Pool tick spacing
  tau: 3  # Reset threshold in ticks
  fee_tier: 0.003  # Pool fee tier (0.3%)
  price_impact_threshold: 0.001  # Threshold for non-arbitrage detection
  batch_size: 32  # Batch size for feature computation
  use_gpu: false  # Whether to use GPU for feature computation if available
  token0_decimals: 18  # Decimals for token0 (e.g., ETH has 18 decimals)
  token1_decimals: 6   # Decimals for token1 (e.g., USDC has 6 decimals)

# Model architecture
model:
  input_dim: 5  # [t/T, ewma_volume, pool_price, center_bucket, wealth]
  hidden_layers: 5
  hidden_units: 16
  activation: "relu"
  output_activation: "softmax"
  learning_rate: 0.001
  optimizer: "adam"
  batch_size: 32
  max_steps: 10000
  patience: 1000  # Early stopping patience
  checkpoint_freq: 100

# Strategy parameters
strategy:
  min_position_size: 0.01  # Minimum position size in ETH
  max_position_size: 10.0  # Maximum position size in ETH
  min_tick_width: 2  # Minimum width of position in ticks
  max_tick_width: 10  # Maximum width of position in ticks
  rebalance_threshold: 0.02  # Price change threshold for rebalancing
  gas_cost: 0.01  # Estimated gas cost in ETH for rebalancing

# Simulator parameters
simulator:
  tau: 3  # Number of buckets for position range
  tick_spacing: 60  # Must match pool tick spacing
  fee_tier: 0.003  # Must match pool fee tier
  initial_price: 1800.0  # Initial ETH price in USD
  initial_liquidity: 100.0  # Initial liquidity in ETH
  min_sqrt_ratio: 4295128739  # Minimum valid sqrtPriceX96
  max_sqrt_ratio: 1461446703485210103287273052203988822378723970342  # Maximum valid sqrtPriceX96
  position_width: 6  # Default width of positions in ticks
  rebalance_cost: 0.01  # Gas cost for rebalancing in ETH

# Utility function
utility:
  risk_aversion: 0.01  # CARA utility risk aversion parameter
  wealth_scale: 1000.0  # Scale factor for wealth normalization

# Logging and output
logging:
  log_dir: "outputs/logs/"
  model_dir: "outputs/models/"
  plot_dir: "outputs/plots/"
  log_level: "INFO"
  plot_freq: 100  # Plot every N episodes
  metrics:
    - "wealth"
    - "fees_collected"
    - "active_positions"
    - "rebalance_count"
    - "utility"
    - "sharpe_ratio"
    - "max_drawdown"

# Performance optimization
performance:
  use_multiprocessing: true  # Enable parallel processing
  num_workers: 4  # Number of worker processes
  prefetch_factor: 2  # Number of batches to prefetch
  pin_memory: true  # Pin memory for faster data transfer to GPU
  persistent_workers: true  # Keep workers alive between epochs

# Random seed for reproducibility
seed: 42 